import autobind from 'autobind-decorator';
import Module from '@/module';
import Message from '@/message';
import serifs from '@/serifs';
import * as seedrandom from 'seedrandom';
import { genItem } from '@/vocabulary';
import * as loki from 'lokijs';
import config from '../../config';

export const blessing = [
	'超吉',
	'大大吉',
	'大吉',
	'吉',
	'中吉',
	'小吉',
	'凶',
	'大凶',
];

const colorData = [
	{ BirthdayColor: "純白", ColorCode: "FFFFFF" },
	{ BirthdayColor: "フロスティホワイト", ColorCode: "E6EAE6" },
	{ BirthdayColor: "シルバーグレイ", ColorCode: "AFAFB0" },
	{ BirthdayColor: "アルミニウムグレイ", ColorCode: "8D9192" },
	{ BirthdayColor: "スチールグレイ", ColorCode: "736D71" },
	{ BirthdayColor: "葡萄鼠", ColorCode: "705B67" },
	{ BirthdayColor: "漆黒", ColorCode: "0D0015" },
	{ BirthdayColor: "シトロンイエロー", ColorCode: "B8C43A" },
	{ BirthdayColor: "苔色", ColorCode: "69821B" },
	{ BirthdayColor: "草色", ColorCode: "7B8D42" },
	{ BirthdayColor: "ミストグリーン", ColorCode: "BDD99F" },
	{ BirthdayColor: "白緑", ColorCode: "D6E9CA" },
	{ BirthdayColor: "パロットグリーン", ColorCode: "37A34A" },
	{ BirthdayColor: "グラスグリーン", ColorCode: "7B8D42" },
	{ BirthdayColor: "深緑", ColorCode: "00552E" },
	{ BirthdayColor: "ホワイトリリー", ColorCode: "F0F6DA" },
	{ BirthdayColor: "萌黄色", ColorCode: "006E54" },
	{ BirthdayColor: "フォーリッジ", ColorCode: "47744B" },
	{ BirthdayColor: "リーフグリーン", ColorCode: "9FC24D" },
	{ BirthdayColor: "フォレストグリーン", ColorCode: "288C66" },
	{ BirthdayColor: "空色", ColorCode: "A0D8EF" },
	{ BirthdayColor: "浅葱色", ColorCode: "00A3AF" },
	{ BirthdayColor: "露草", ColorCode: "38A1DB" },
	{ BirthdayColor: "鴨の羽色", ColorCode: "00688B" },
	{ BirthdayColor: "濃藍", ColorCode: "0F2350" },
	{ BirthdayColor: "クリーム", ColorCode: "E3D7A3" },
	{ BirthdayColor: "ペールレモン", ColorCode: "FEF400" },
	{ BirthdayColor: "タンポポ色", ColorCode: "FFD900" },
	{ BirthdayColor: "若草色", ColorCode: "C3D825" },
	{ BirthdayColor: "メドーグリーン", ColorCode: "529C47" },
	{ BirthdayColor: "若芽", ColorCode: "E0EBAF" },
	{ BirthdayColor: "コーンフラワーブルー", ColorCode: "3F4E93" },
	{ BirthdayColor: "若紫", ColorCode: "BC64A4" },
	{ BirthdayColor: "ディープローヤルブルー", ColorCode: "21297E" },
	{ BirthdayColor: "紅藤色", ColorCode: "CCA6BF" },
	{ BirthdayColor: "パンジーパープル", ColorCode: "50347E" },
	{ BirthdayColor: "ペールライラック", ColorCode: "DEBDD8" },
	{ BirthdayColor: "モーベット", ColorCode: "B269A1" },
	{ BirthdayColor: "バーガンディー", ColorCode: "6C2735" },
	{ BirthdayColor: "フクシャパープル", ColorCode: "EA4A6E" },
	{ BirthdayColor: "ローズレッド", ColorCode: "EA618E" },
	{ BirthdayColor: "紅色", ColorCode: "D3336F" },
	{ BirthdayColor: "カーミン", ColorCode: "D5345E" },
	{ BirthdayColor: "うぐいす色", ColorCode: "878F15" },
	{ BirthdayColor: "海松色", ColorCode: "726D40" },
	{ BirthdayColor: "勿忘草色", ColorCode: "89C3EB" },
	{ BirthdayColor: "スモークブルー", ColorCode: "A4C1D7" },
	{ BirthdayColor: "スマルト", ColorCode: "4C5E74" },
	{ BirthdayColor: "チョコレート", ColorCode: "6C3524" },
	{ BirthdayColor: "紺色", ColorCode: "223A70" },
	{ BirthdayColor: "鳥の子色", ColorCode: "FFF1CF" },
	{ BirthdayColor: "ライムライト", ColorCode: "FFF799" },
	{ BirthdayColor: "鬱金色", ColorCode: "FABF14" },
	{ BirthdayColor: "菜の花色", ColorCode: "FFEC47" },
	{ BirthdayColor: "リードグリーン", ColorCode: "D8E2AE" },
	{ BirthdayColor: "ミストホワイト", ColorCode: "E5E8E1" },
	{ BirthdayColor: "裏葉色", ColorCode: "BECEBC" },
	{ BirthdayColor: "柳茶", ColorCode: "A1A46D" },
	{ BirthdayColor: "オリーブグリーン", ColorCode: "5F6527" },
	{ BirthdayColor: "アイビーグリーン", ColorCode: "578A3D" },
	{ BirthdayColor: "一斤染", ColorCode: "F5B199" },
	{ BirthdayColor: "ベビーピンク", ColorCode: "FDEDE4" },
	{ BirthdayColor: "鴇色", ColorCode: "F4B3C2" },
	{ BirthdayColor: "ポピーレッド", ColorCode: "EA5550" },
	{ BirthdayColor: "チェリーレッド", ColorCode: "CF0125" },
	{ BirthdayColor: "桜色", ColorCode: "FEF4F4" },
	{ BirthdayColor: "サーモンピンク", ColorCode: "F3A68C" },
	{ BirthdayColor: "紅梅色", ColorCode: "F2A0A1" },
	{ BirthdayColor: "珊瑚色", ColorCode: "F5B1AA" },
	{ BirthdayColor: "シグナルレッド", ColorCode: "E8383D" },
	{ BirthdayColor: "砥粉色", ColorCode: "F4DDA5" },
	{ BirthdayColor: "オレンジバーミリオン", ColorCode: "E65454" },
	{ BirthdayColor: "柿色", ColorCode: "ED6D3D" },
	{ BirthdayColor: "スカーレッド", ColorCode: "E23620" },
	{ BirthdayColor: "ルージュ", ColorCode: "D11C1E" },
	{ BirthdayColor: "薄紅藤", ColorCode: "D2A4C8" },
	{ BirthdayColor: "モーブ", ColorCode: "915DA3" },
	{ BirthdayColor: "カンパヌラパープル", ColorCode: "985B9E" },
	{ BirthdayColor: "ビオレ", ColorCode: "581074" },
	{ BirthdayColor: "古代紫", ColorCode: "895B8A" },
	{ BirthdayColor: "ペールオーキッド", ColorCode: "AAA7D0" },
	{ BirthdayColor: "ディープモーベット", ColorCode: "BA64A0" },
	{ BirthdayColor: "江戸紫", ColorCode: "745399" },
	{ BirthdayColor: "マロー", ColorCode: "934491" },
	{ BirthdayColor: "ワインレッド", ColorCode: "B33E5C" },
	{ BirthdayColor: "シルバーグリーン", ColorCode: "CAE2C6" },
	{ BirthdayColor: "オパールグリーン", ColorCode: "BEE0CE" },
	{ BirthdayColor: "ペールアクア", ColorCode: "A7D3CF" },
	{ BirthdayColor: "スプレーグリーン", ColorCode: "A3D3DD" },
	{ BirthdayColor: "パステルブルー", ColorCode: "49BDF0" },
	{ BirthdayColor: "ストロー", ColorCode: "ECE093" },
	{ BirthdayColor: "薄桜", ColorCode: "FDEFF2" },
	{ BirthdayColor: "シェルピンク", ColorCode: "FBDAC8" },
	{ BirthdayColor: "フクシャピンク", ColorCode: "F5A0BD" },
	{ BirthdayColor: "ディープオーキッドピンク", ColorCode: "E383A4" },
	{ BirthdayColor: "青藤色", ColorCode: "84A2D4" },
	{ BirthdayColor: "チョークブルー", ColorCode: "68A9CF" },
	{ BirthdayColor: "白百合", ColorCode: "FDFCF5" },
	{ BirthdayColor: "薄緑色", ColorCode: "69B076" },
	{ BirthdayColor: "支子色", ColorCode: "FBCA4D" },
	{ BirthdayColor: "パンプキン", ColorCode: "E5A323" },
	{ BirthdayColor: "蒸栗色", ColorCode: "ECDECF" },
	{ BirthdayColor: "利休白茶", ColorCode: "A29779" },
	{ BirthdayColor: "フロスティグレイ", ColorCode: "E8ECE9" },
	{ BirthdayColor: "鼠色", ColorCode: "949495" },
	{ BirthdayColor: "ペールミストホワイト", ColorCode: "D5DAD4" },
	{ BirthdayColor: "スカイグレイ", ColorCode: "CBD0D3" },
	{ BirthdayColor: "バトルシップグレイ", ColorCode: "898989" },
	{ BirthdayColor: "スレートグレイ", ColorCode: "626063" },
	{ BirthdayColor: "消炭色", ColorCode: "524E4D" },
	{ BirthdayColor: "若苗色", ColorCode: "C7DC68" },
	{ BirthdayColor: "若菜色", ColorCode: "D8E698" },
	{ BirthdayColor: "鸚緑", ColorCode: "A2BD08" },
	{ BirthdayColor: "葦葉色", ColorCode: "88CB9D" },
	{ BirthdayColor: "スプラウト", ColorCode: "A3D49C" },
	{ BirthdayColor: "エルブ", ColorCode: "79C288" },
	{ BirthdayColor: "ディープピーグリーン", ColorCode: "79C266" },
	{ BirthdayColor: "エメラルドグリーン", ColorCode: "00A968" },
	{ BirthdayColor: "ターコイズグリーン", ColorCode: "00947A" },
	{ BirthdayColor: "薄浅葱", ColorCode: "A5D8E0" },
	{ BirthdayColor: "アジュールブルー", ColorCode: "00B2BC" },
	{ BirthdayColor: "ターコイズ", ColorCode: "009B9F" },
	{ BirthdayColor: "マラカイトグリーン", ColorCode: "009854" },
	{ BirthdayColor: "ティールグリーン", ColorCode: "01686D" },
	{ BirthdayColor: "小鴨色", ColorCode: "014127" },
	{ BirthdayColor: "水色", ColorCode: "BCE2E8" },
	{ BirthdayColor: "フォゲットミーナットブルー", ColorCode: "70C6F5" },
	{ BirthdayColor: "群青色", ColorCode: "005BAA" },
	{ BirthdayColor: "千歳緑", ColorCode: "316745" },
	{ BirthdayColor: "パラキートグリーン", ColorCode: "2CB232" },
	{ BirthdayColor: "エッグシェル", ColorCode: "F5F6CA" },
	{ BirthdayColor: "レタスグリーン", ColorCode: "D1DE4C" },
	{ BirthdayColor: "シャルトルーズイエロー", ColorCode: "E3E548" },
	{ BirthdayColor: "枯草色", ColorCode: "E4DC8A" },
	{ BirthdayColor: "オリーブ", ColorCode: "72640C" },
	{ BirthdayColor: "コロニアルイエロー", ColorCode: "D0C67C" },
	{ BirthdayColor: "ペールマスタード", ColorCode: "A49627" },
	{ BirthdayColor: "ゴールデンオーカー", ColorCode: "8D6F2F" },
	{ BirthdayColor: "オリーブ茶", ColorCode: "464646" },
	{ BirthdayColor: "千歳茶", ColorCode: "494A41" },
	{ BirthdayColor: "ディープアクア", ColorCode: "8CCAB0" },
	{ BirthdayColor: "緑青色", ColorCode: "47885E" },
	{ BirthdayColor: "スプルースグリーン", ColorCode: "036122" },
	{ BirthdayColor: "ボトルグリーン", ColorCode: "034415" },
	{ BirthdayColor: "サイプレスグリーン", ColorCode: "264939" },
	{ BirthdayColor: "ネープルズイエロー", ColorCode: "FACE9D" },
	{ BirthdayColor: "マリーゴールドイエロー", ColorCode: "F9CC77" },
	{ BirthdayColor: "山吹色", ColorCode: "F8B500" },
	{ BirthdayColor: "オールドゴールド", ColorCode: "B36029" },
	{ BirthdayColor: "コーヒーブラウン", ColorCode: "7A5347" },
	{ BirthdayColor: "灰桜", ColorCode: "E8D3D1" },
	{ BirthdayColor: "薄紅", ColorCode: "F0908D" },
	{ BirthdayColor: "ペールクロッカス", ColorCode: "BEA2CA" },
	{ BirthdayColor: "菫色", ColorCode: "7058A3" },
	{ BirthdayColor: "プルプル", ColorCode: "5C1767" },
	{ BirthdayColor: "ペールホワイトリリー", ColorCode: "F7F7D9" },
	{ BirthdayColor: "ペールフレッシュグリーン", ColorCode: "DDEAB2" },
	{ BirthdayColor: "メロンイエロー", ColorCode: "E0DE94" },
	{ BirthdayColor: "エルムグリーン", ColorCode: "657D61" },
	{ BirthdayColor: "オリーブドラブ", ColorCode: "665A1A" },
	{ BirthdayColor: "クリーム", ColorCode: "FFF8A8" },
	{ BirthdayColor: "レモンイエロー", ColorCode: "FFF352" },
	{ BirthdayColor: "黄水仙", ColorCode: "F6D700" },
	{ BirthdayColor: "サフランイエロー", ColorCode: "FAC559" },
	{ BirthdayColor: "向日葵色", ColorCode: "FCC800" },
	{ BirthdayColor: "アイボリー", ColorCode: "F8F4E6" },
	{ BirthdayColor: "ライトアプリコット", ColorCode: "F7B894" },
	{ BirthdayColor: "黄土色", ColorCode: "C39143" },
	{ BirthdayColor: "オールドローズ", ColorCode: "E29399" },
	{ BirthdayColor: "マホガニーブラウン", ColorCode: "724943" },
	{ BirthdayColor: "卵色", ColorCode: "FCD575" },
	{ BirthdayColor: "サンライトイエロー", ColorCode: "F19D45" },
	{ BirthdayColor: "金茶", ColorCode: "F39800" },
	{ BirthdayColor: "ガーネットブラウン", ColorCode: "973B2C" },
	{ BirthdayColor: "海老茶", ColorCode: "773C30" },
	{ BirthdayColor: "ライトオーキッドピンク", ColorCode: "F9BDC5" },
	{ BirthdayColor: "ペールチェリーピンク", ColorCode: "E1849E" },
	{ BirthdayColor: "カーネーションピンク", ColorCode: "EB5381" },
	{ BirthdayColor: "ローズピンク", ColorCode: "F19CA7" },
	{ BirthdayColor: "ペッパーレッド", ColorCode: "CF0141" },
	{ BirthdayColor: "ベビーブルー", ColorCode: "BBE2F1" },
	{ BirthdayColor: "薄群青", ColorCode: "5383C3" },
	{ BirthdayColor: "ダックブルー", ColorCode: "007199" },
	{ BirthdayColor: "コバルトブルー", ColorCode: "0068B7" },
	{ BirthdayColor: "インクブルー", ColorCode: "003F8E" },
	{ BirthdayColor: "アクア", ColorCode: "3FB5D3" },
	{ BirthdayColor: "ペールサックスブルー", ColorCode: "4593A0" },
	{ BirthdayColor: "新橋色", ColorCode: "59B9C6" },
	{ BirthdayColor: "ブルーカナール", ColorCode: "016171" },
	{ BirthdayColor: "マリンブルー", ColorCode: "006888" },
	{ BirthdayColor: "パールホワイト", ColorCode: "F7F6F5" },
	{ BirthdayColor: "ペールパステルブルー", ColorCode: "608FC3" },
	{ BirthdayColor: "ラベンダーブルー", ColorCode: "5371AD" },
	{ BirthdayColor: "マジョリカブルー", ColorCode: "044182" },
	{ BirthdayColor: "紺青", ColorCode: "192F60" },
	{ BirthdayColor: "ディープベビーピンク", ColorCode: "FDEDE4" },
	{ BirthdayColor: "ペールモーベット", ColorCode: "B370A6" },
	{ BirthdayColor: "ライラックパープル", ColorCode: "B88FAD" },
	{ BirthdayColor: "ワインレッド", ColorCode: "B13A55" },
	{ BirthdayColor: "ポピーレッド", ColorCode: "E83F6F" },
	{ BirthdayColor: "バーガンディー", ColorCode: "8A2232" },
	{ BirthdayColor: "サーモンピンク", ColorCode: "E95C59" },
	{ BirthdayColor: "紅梅色", ColorCode: "E26D8D" },
	{ BirthdayColor: "チャイニーズレッド", ColorCode: "DA1B60" },
	{ BirthdayColor: "トマトレッド", ColorCode: "E73170" },
	{ BirthdayColor: "チェリーレッド", ColorCode: "DA0F47" },
	{ BirthdayColor: "ピンクベージュ", ColorCode: "F3D6C1" },
	{ BirthdayColor: "コロニアルローズ", ColorCode: "D8C3A5" },
	{ BirthdayColor: "アプリコット", ColorCode: "F39B71" },
	{ BirthdayColor: "ゴールド", ColorCode: "E6B422" },
	{ BirthdayColor: "キャメル", ColorCode: "AC8D48" },
	{ BirthdayColor: "タン", ColorCode: "B28050" },
	{ BirthdayColor: "アッシュグレイ", ColorCode: "9E9E9E" },
	{ BirthdayColor: "グラニットグレイ", ColorCode: "7E7E7E" },
	{ BirthdayColor: "スレートグレイ", ColorCode: "5B5B5B" },
	{ BirthdayColor: "鉛色", ColorCode: "4C4C4C" },
	{ BirthdayColor: "モスグリーン", ColorCode: "A2AD68" },
	{ BirthdayColor: "若竹色", ColorCode: "7D945D" },
	{ BirthdayColor: "エメラルドグリーン", ColorCode: "00A963" },
	{ BirthdayColor: "ペパーミントグリーン", ColorCode: "AFD5AA" },
	{ BirthdayColor: "セージグリーン", ColorCode: "8DA987" },
	{ BirthdayColor: "深緑", ColorCode: "00552E" },
	{ BirthdayColor: "アスパラガスグリーン", ColorCode: "6A943C" },
	{ BirthdayColor: "アップルグリーン", ColorCode: "A2D141" },
	{ BirthdayColor: "キンモクセイ色", ColorCode: "E9BA30" },
	{ BirthdayColor: "オリーブイエロー", ColorCode: "A4A42B" },
	{ BirthdayColor: "キウイグリーン", ColorCode: "8DB600" },
	{ BirthdayColor: "ライトリーフグリーン", ColorCode: "96C57F" },
	{ BirthdayColor: "クロムイエロー", ColorCode: "FFD300" },
	{ BirthdayColor: "バナナイエロー", ColorCode: "FFC425" },
	{ BirthdayColor: "ライムイエロー", ColorCode: "DDE826" },
	{ BirthdayColor: "シャーベットイエロー", ColorCode: "F9DC24" },
	{ BirthdayColor: "パステルイエロー", ColorCode: "F6E100" },
	{ BirthdayColor: "ヴァニライエロー", ColorCode: "F3E6B0" },
	{ BirthdayColor: "トパーズ", ColorCode: "D2A82E" },
	{ BirthdayColor: "ハニーブラウン", ColorCode: "CB7741" },
	{ BirthdayColor: "オレンジオーカー", ColorCode: "C25E00" },
	{ BirthdayColor: "モカブラウン", ColorCode: "705242" },
	{ BirthdayColor: "エンジレッド", ColorCode: "CA2A40" },
	{ BirthdayColor: "ルビーレッド", ColorCode: "9B111E" },
	{ BirthdayColor: "スカーレット", ColorCode: "D81E05" },
	{ BirthdayColor: "ブラッドオレンジ", ColorCode: "E85A4F" },
	{ BirthdayColor: "ココアブラウン", ColorCode: "6C503E" },
	{ BirthdayColor: "ベージュ", ColorCode: "DAC0A8" },
	{ BirthdayColor: "ペールピンク", ColorCode: "F8C3CD" },
	{ BirthdayColor: "カメリアピンク", ColorCode: "DE7185" },
	{ BirthdayColor: "アカネ色", ColorCode: "C28E95" },
	{ BirthdayColor: "ピンクベージュ", ColorCode: "DBCBB5" },
	{ BirthdayColor: "キャメルベージュ", ColorCode: "BFA46F" },
	{ BirthdayColor: "バーミリオン", ColorCode: "E85405" },
	{ BirthdayColor: "スカーレッド", ColorCode: "E8522E" },
	{ BirthdayColor: "ベビーチーク", ColorCode: "CBA8A3" },
	{ BirthdayColor: "ローズウッド", ColorCode: "A35C6E" },
	{ BirthdayColor: "コーラルピンク", ColorCode: "FF6B6B" },
	{ BirthdayColor: "コーラルレッド", ColorCode: "FF6F61" },
	{ BirthdayColor: "ルビーレッド", ColorCode: "CF3636" },
	{ BirthdayColor: "ガーネット", ColorCode: "9A2530" },
	{ BirthdayColor: "マルーン", ColorCode: "842729" },
	{ BirthdayColor: "ダークチョコレート", ColorCode: "3A1C1C" },
	{ BirthdayColor: "紺藍", ColorCode: "223A70" },
	{ BirthdayColor: "パウダーブルー", ColorCode: "BBDDE6" },
	{ BirthdayColor: "スカイブルー", ColorCode: "A0D8EF" },
	{ BirthdayColor: "セルリアンブルー", ColorCode: "00AEEF" },
	{ BirthdayColor: "ターコイズブルー", ColorCode: "00A2AE" },
	{ BirthdayColor: "アクアブルー", ColorCode: "66D9E8" },
	{ BirthdayColor: "シャドウブルー", ColorCode: "6487A8" },
	{ BirthdayColor: "アイリスブルー", ColorCode: "5B93A5" },
	{ BirthdayColor: "ナイルブルー", ColorCode: "267C8B" },
	{ BirthdayColor: "トパーズブルー", ColorCode: "00749E" },
	{ BirthdayColor: "セレスチャルブルー", ColorCode: "3399CC" },
	{ BirthdayColor: "ラベンダーブルー", ColorCode: "7B6FAB" },
	{ BirthdayColor: "ラベンダーアイス", ColorCode: "9FACD6" },
	{ BirthdayColor: "エレクトリックブルー", ColorCode: "247ABD" },
	{ BirthdayColor: "マリンブルー", ColorCode: "0067A5" },
	{ BirthdayColor: "スチールブルー", ColorCode: "006699" },
	{ BirthdayColor: "ナイトブルー", ColorCode: "000C40" },
	{ BirthdayColor: "ミッドナイトブルー", ColorCode: "003A6C" },
	{ BirthdayColor: "ディープベビーピンク", ColorCode: "F9CCCA" },
	{ BirthdayColor: "ペールモーヴ", ColorCode: "C09AB7" },
	{ BirthdayColor: "オーキッドピンク", ColorCode: "DE99B1" },
	{ BirthdayColor: "ビビットピンク", ColorCode: "D767AD" },
	{ BirthdayColor: "ウィスタリア", ColorCode: "8A6BBE" },
	{ BirthdayColor: "バイオレット", ColorCode: "835EAD" },
	{ BirthdayColor: "深紫", ColorCode: "280C3B" },
	{ BirthdayColor: "アンバーレッド", ColorCode: "CD2220" },
	{ BirthdayColor: "オレンジレッド", ColorCode: "FF4F00" },
	{ BirthdayColor: "サイプレス", ColorCode: "4A503D" },
	{ BirthdayColor: "シトリンイエロー", ColorCode: "FFD200" },
	{ BirthdayColor: "パステルグリーン", ColorCode: "B6D541" },
	{ BirthdayColor: "スプリンググリーン", ColorCode: "00AC47" },
	{ BirthdayColor: "フレッシュグリーン", ColorCode: "00A554" },
	{ BirthdayColor: "ジャスミン", ColorCode: "E4D5D3" },
	{ BirthdayColor: "トパーズイエロー", ColorCode: "FFC40A" },
	{ BirthdayColor: "ターメリック", ColorCode: "D1903C" },
	{ BirthdayColor: "オレンジブラウン", ColorCode: "A65E2E" },
	{ BirthdayColor: "ダークオレンジ", ColorCode: "A85100" },
	{ BirthdayColor: "シナモン", ColorCode: "8A3B00" },
	{ BirthdayColor: "レイクグリーン", ColorCode: "007849" },
	{ BirthdayColor: "ミントグリーン", ColorCode: "AFDBB1" },
	{ BirthdayColor: "ペールシーグリーン", ColorCode: "A8D8B9" },
	{ BirthdayColor: "アイビーグリーン", ColorCode: "5E7C5E" },
	{ BirthdayColor: "フォレストグリーン", ColorCode: "225D35" },
	{ BirthdayColor: "マラカイトグリーン", ColorCode: "007A6E" },
	{ BirthdayColor: "ターコイズグリーン", ColorCode: "00A17D" },
	{ BirthdayColor: "ミントブルー", ColorCode: "B0E57C" },
	{ BirthdayColor: "チャートリュース", ColorCode: "A6D76A" },
	{ BirthdayColor: "スプリングブリーズ", ColorCode: "D3E8DA" },
	{ BirthdayColor: "パラカ", ColorCode: "B5EAD7" },
	{ BirthdayColor: "セピア", ColorCode: "704214" },
	{ BirthdayColor: "ペールチェリー", ColorCode: "F5E1E0" },
	{ BirthdayColor: "パーティーキャンディ", ColorCode: "FFA3B5" },
	{ BirthdayColor: "パステルローズ", ColorCode: "FDC8DB" },
	{ BirthdayColor: "ラズベリーピンク", ColorCode: "D61753" },
	{ BirthdayColor: "ワインカラー", ColorCode: "6B2849" },
	{ BirthdayColor: "ヴィンテージローズ", ColorCode: "D8A3A3" },
	{ BirthdayColor: "オールドピンク", ColorCode: "C89898" },
	{ BirthdayColor: "ディープローズ", ColorCode: "B74571" },
	{ BirthdayColor: "バーガンディー", ColorCode: "7E263D" },
	{ BirthdayColor: "ブラック", ColorCode: "000000" },
	{ BirthdayColor: "スモークグレイ", ColorCode: "726A6D" },
	{ BirthdayColor: "セピアグレイ", ColorCode: "695644" },
	{ BirthdayColor: "グラファイトグレイ", ColorCode: "373536" },
	{ BirthdayColor: "ジェットブラック", ColorCode: "161616" },
	{ BirthdayColor: "パールホワイト", ColorCode: "F7F6F5" },
	{ BirthdayColor: "クリーム", ColorCode: "FFF8A8" },
	{ BirthdayColor: "ペールレモン", ColorCode: "FFF299" },
	{ BirthdayColor: "カナリアイエロー", ColorCode: "FFD200" },
	{ BirthdayColor: "ライトオレンジ", ColorCode: "FFB74D" },
	{ BirthdayColor: "コーラルイエロー", ColorCode: "FFB769" },
	{ BirthdayColor: "サーモンピンク", ColorCode: "FF8C61" },
	{ BirthdayColor: "ライトピンク", ColorCode: "FFB6C1" },
	{ BirthdayColor: "桜色", ColorCode: "FEDFE1" },
	{ BirthdayColor: "ライトラベンダー", ColorCode: "DFB1FF" },
	{ BirthdayColor: "薄紫", ColorCode: "B196D6" },
	{ BirthdayColor: "淡葡萄色", ColorCode: "A891C3" },
	{ BirthdayColor: "モーブ", ColorCode: "CB99C9" },
	{ BirthdayColor: "ペールグレープ", ColorCode: "D3A0C4" },
	{ BirthdayColor: "アルカンセル", ColorCode: "F4CACA" },
	{ BirthdayColor: "サーモンピンク", ColorCode: "FF9671" },
	{ BirthdayColor: "コーラルピンク", ColorCode: "FF6B6B" },
	{ BirthdayColor: "ローズピンク", ColorCode: "FFA6A6" },
	{ BirthdayColor: "ラズベリーレッド", ColorCode: "E51837" },
	{ BirthdayColor: "ディープレッド", ColorCode: "A80734" },
	{ BirthdayColor: "オールドレッド", ColorCode: "8C2D29" },
	{ BirthdayColor: "チョコレートブラウン", ColorCode: "6B3B1F" },
	{ BirthdayColor: "モカブラウン", ColorCode: "5E433F" },
	{ BirthdayColor: "テラコッタ", ColorCode: "B76F40" },
	{ BirthdayColor: "バーントシェンナ", ColorCode: "AB5C36" },
	{ BirthdayColor: "ラスタ", ColorCode: "794D39" },
	{ BirthdayColor: "シリカ", ColorCode: "C4A43D" },
	{ BirthdayColor: "ブロンズイエロー", ColorCode: "B26D33" },
	{ BirthdayColor: "オリーブ", ColorCode: "4E4B28" },
	{ BirthdayColor: "アボカド", ColorCode: "568203" },
	{ BirthdayColor: "スピリチュアルグリーン", ColorCode: "00A168" },
	{ BirthdayColor: "ライトグリーン", ColorCode: "A9DFBF" },
	{ BirthdayColor: "アクアマリン", ColorCode: "6EE7B7" },
	{ BirthdayColor: "シーグリーン", ColorCode: "00A28A" },
	{ BirthdayColor: "ティール", ColorCode: "008080" },
	{ BirthdayColor: "ターコイズ", ColorCode: "40E0D0" },
	{ BirthdayColor: "サマーシーグリーン", ColorCode: "18A98E" },
	{ BirthdayColor: "ミントブルー", ColorCode: "98D8D8" },
	{ BirthdayColor: "スチールブルー", ColorCode: "4682B4" },
	{ BirthdayColor: "セレスチャルブルー", ColorCode: "4997D0" },
	{ BirthdayColor: "セピアグレイ", ColorCode: "704214" },
	{ BirthdayColor: "モクグレー", ColorCode: "5A5349" },
	{ BirthdayColor: "チャコールグレー", ColorCode: "4E443C" },
	{ BirthdayColor: "アイアンブラック", ColorCode: "25282E" },
	{ BirthdayColor: "コールドブラック", ColorCode: "1F1F1F" },
	{ BirthdayColor: "ウォームブラック", ColorCode: "0F0F0F" },
  ];

export default class extends Module {
	public readonly name = 'fortune';

	private learnedKeywords?: loki.Collection<{
		keyword: string;
		learnedAt: number;
	}>;

	@autobind
	public install() {
		if (config.keywordEnabled) {
			this.learnedKeywords = this.ai.getCollection('_keyword_learnedKeywords', {
				indices: ['userId']
			});
		}

		return {
			mentionHook: this.mentionHook
		};
	}

	@autobind
	private async mentionHook(msg: Message) {
		if (msg.includes(['占', 'うらな', '運勢', 'おみくじ'])) {
			const getKeyword = (rng: () => number) => {
				if (!this.learnedKeywords) return null;
	
				const count = this.learnedKeywords.count();
				const offset = Math.floor(rng() * count);
		
				const x = this.learnedKeywords.chain().find().offset(offset).limit(1).data();
				const keyword = x[0]?.keyword || null;
				return keyword;
			};

			const date = new Date();
			const seed = `${date.getFullYear()}/${date.getMonth()}/${date.getDate()}@${msg.userId}@${this.ai.account.id}`;
			const rng = seedrandom(seed);
			const omikuji = blessing[Math.floor(rng() * blessing.length)];
			const item = genItem(rng, getKeyword);

		// ランダムな色を選択
			const randomColorIndex = Math.floor(rng() * colorData.length);
			const selectedColor = colorData[randomColorIndex].ColorCode;
			const selectedColorName = colorData[randomColorIndex].BirthdayColor;

			msg.reply(`**${omikuji}🎉**\nラッキーアイテム: ${item}\nラッキーカラー: ${selectedColorName} $[bg.color=${selectedColor}  ${selectedColor} ]`, {
				cw: serifs.fortune.cw(msg.friend.name)
			});
			return true;
		} else {
			return false;
		}
	}
}
